### ISSUE TITLE
Proposals for fork

### ISSUE THREAD

**Issue by Levdbas** [smithfield-studio/acf-svg-icon-picker#1]
Hi @mike-sheppard ,

I went over the plugin and these are the most important changes I would like to suggest, ordered from the most important to least. As said before, I can provide PR's for this but I first would like to discuss with you how you see my suggested changes.

- [x] #3
- [x] ~~#4~~ (reverted the revert 😅)
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [ ] #10

---

@Levdbas Edit: Especially the first two would be a priority for me personally, I have 15 projects that are currently running this plugin where the icon picker is currently not working and I am not really fond of downgrading ACF if there is a solution at hand. I'd rather swap out the plugin via Composer. 👯 

@mike-sheppard **Edit**: converted the list into individual issues

**Comment by mike-sheppard** [comment]
hey @Levdbas sounds great!

No problems on my side with any of these changes. I'll jump on #2 today + feel free to add a PR for the others, and I'll get 'em merged in :)

**Comment by Levdbas** [comment]
I'll do that first thing tomorrow @mike-sheppard

**Comment by mike-sheppard** [comment]
thanks, hopefully all workin ok now, pushed up some quick fixes

**Comment by Levdbas** [comment]
Only seeing the main branch, no dev-main. Let me know!

**Comment by mike-sheppard** [comment]
ah yeah sorry, yep `main` (`dev-main` if using it via composer)

```yml
"repositories": {
    "acf-svg-icon-picker": {
        "type": "git",
        "url": "https://github.com/smithfield-studio/acf-svg-icon-picker"
    },

...

"require": {
    "smithfield-studio/acf-svg-icon-picker": "dev-main",
}
```
